spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: alexander19206r@gmail.com
    password: zjbz mtgt brrv skco
    properties:
      # These must explicitly match the standard jakarta.mail property strings
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ec.notification_service.event.OrderCreatedEvent
