server:
  port: 5384

jwt:
  secret: mAdFcl+taWNe3S5W8zoQ1Fu5QrGyZHTvC6HhXFhfQGw
  expirationMs: 3600000

spring:

  data:
    redis:
      host: redis
      port: 6379
  application:
    name: orderProc

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.type.mapping: >
        passwordResetEvent:com.ec.orderProc.payload.PasswordResetEvent,
        orderCreatedEvent:com.ec.orderProc.payload.OrderCreatedEvent

  datasource:
    url: jdbc:postgresql://localhost:5455/orderdb
    username: orderuser
    password: orderpass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: trace       
    org.springframework.security.web: trace   

geocoding:
  nominating-url: https://nominatim.openstreetmap.org
  user-agent: "OrderOpsPlatform/1.0 (learning project; contact: alexander19206r@gmail.com)"